### ISSUE TITLE
List of attendees is always empty

### ISSUE THREAD

**Issue by lshnsk** [ramonvasc/MXLCalendarManagerSwift#3]
Seems that the error occurs in **MXLCalendarManager.swift** (line 110):
```
guard let roleEnum = Role(rawValue: role) else {
        return nil
}
```

Instance of **Role** enum can't be created with values like _"=CHAIR"_, _"=REQ-PARTICIPANT"_ and etc.
![Screen Shot 2019-04-25 at 15 00 20](https://user-images.githubusercontent.com/2272083/56734198-dccb0e00-676a-11e9-8002-006a1da88e05.png)

**Comment by ramonvasc** [comment]
Thanks for reporting I'll try to fix this as soon as I have some spare time.

**Comment by ramonvasc** [comment]
https://github.com/ramonvasc/MXLCalendarManagerSwift/pull/11 Contains the fix for this
