### ISSUE TITLE
Frequency DAILY not handled in checkDate

### ISSUE THREAD

**Issue by jessicathrasher** [ramonvasc/MXLCalendarManagerSwift#5]
The DAILY_FREQUENCY in MXLCalendarEvent is never used, meaning that RRULES like this "RRULE:FREQ=DAILY;UNTIL=20190629T110000Z" don't work. Is there any known reason for this @ramonvasc ?

**Comment by ramonvasc** [comment]
> The DAILY_FREQUENCY in MXLCalendarEvent is never used, meaning that RRULES like this "RRULE:FREQ=DAILY;UNTIL=20190629T110000Z" don't work. Is there any known reason for this @ramonvasc ?

This is actually a bug, thanks for reporting. I'll try to fix it as soon as I have some spare time.

**Comment by minhd-gh** [comment]
I have a fix for this ready. Will put it up as soon as https://github.com/ramonvasc/MXLCalendarManagerSwift/pull/6 is resolved.

**Comment by ramonvasc** [comment]
The library has been updated with the fix from @minhd-gh.

**Comment by minhd-gh** [comment]
https://github.com/ramonvasc/MXLCalendarManagerSwift/pull/7 has the fix.
