### ISSUE TITLE
DESCRIPTION;ENCODING=QUOTED-PRINTABLE:

### ISSUE THREAD

**Issue by GDGapps** [ramonvasc/MXLCalendarManagerSwift#9]
The manager fails to detect the text when the description tag is the following "DESCRIPTION;ENCODING=QUOTED-PRINTABLE:"

**Comment by ramonvasc** [comment]
Could you provide more details about this? At a first look this pattern doesn't seem to follow the standard pattern for Description [https://www.kanzaki.com/docs/ical/description.html](url)

**Comment by GDGapps** [comment]
I am not too familiar with ical, but my university uses such tag. I think it's for description which have new lines.

This is what I get from them:


BEGIN:VCALENDAR
PRODID:-//sciences-po.fr/NONSGML DSI Calendar V1.0//FR
VERSION:2.0

BEGIN:VEVENT
UID:2018101539720180906T132000
SUMMARY:15397 - 19th Century in Europe and Asia: Revolutions, Empires and Nations (the)
CATEGORIES:Cours magistral
DESCRIPTION;ENCODING=QUOTED-PRINTABLE:Enseignant(s) :\n - SCHEMPER Lukas\n\nEnseignement :\n - AHIS 12A00 - 19th Century in Europe and Asia: Revolutions, Empires and Nations (the) - 201810
DTSTART;TZID=Europe/Paris:20180906T132000
DTEND;TZID=Europe/Paris:20180906T152000
LOCATION:Salle : GRAND AMPH - 77 rue Bellot - 76600 Le Havre
END:VEVENT
